sonar.projectKey=93wilsonlu_OJ
sonar.organization=ste2bbd6xw8ksm

sonar.projectName=OJ

# Path is relative to the sonar-project.properties file
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/tests

# Exclude specific files or directories
sonar.exclusions=backend/venv/**,frontend/node_modules/**,**/__pycache__/**

# Python configuration
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml

# JS/TS configuration
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
