sonar.projectKey=93wilsonlu_OJ
sonar.organization=93wilsonlu

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/tests,backend/tests
sonar.exclusions=frontend/dist/**,frontend/node_modules/**,backend/.venv/**,backend/app/migrations/**
sonar.test.inclusions=frontend/tests/**/*.ts,frontend/tests/**/*.tsx,backend/tests/**/*.py

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
