apiVersion: v1
kind: ServiceAccount
metadata:
  name: judge-worker-ksa
  namespace: default
  annotations:
    # Replace PROJECT_ID with your GCP project ID.
    iam.gke.io/gcp-service-account: judge-worker@project-6d617c10-fed9-46d4-b8e.iam.gserviceaccount.com
